### ISSUE TITLE
tag中包含空格时会导致tag词匹配出现异常

### ISSUE THREAD

**Issue by pineoncellar** [cypress0522/AImage#1]
如题，当tag中包含空格，如 `.naifu:best quality` 时，tag词匹配出现异常，骰娘回复：`[CQ:image,file=�������ʷ�����ʱ���ִ���! HTTP״̬��: 400]` 或程序直接崩溃

![QQ截图20221125091032](https://user-images.githubusercontent.com/116723741/203881185-fbb9197f-e856-4057-ba17-926b385920f2.png)

![QQ截图20221125091344](https://user-images.githubusercontent.com/116723741/203884630-a3068f79-b4b7-4679-9516-03de13052620.png)

似乎与大括号无关。

![QQ截图20221125095536](https://user-images.githubusercontent.com/116723741/203884866-a54efb60-3ca4-467a-bc19-36eccfb30250.png)

当把括号替换为下划线，程序正常运行。

![QQ截图20221125095806](https://user-images.githubusercontent.com/116723741/203885112-7bebf334-f1e1-4eee-b1e7-ae99b9450615.png)

附一张lua插件正常使用的截图：

![QQ截图20221125091603](https://user-images.githubusercontent.com/116723741/203881460-84fb3e88-5ac8-4879-9975-804b928f7b28.png)

**Comment by HsiangNianian** [comment]
考虑使用单lua文件版本
