### ISSUE TITLE
mod update AImage报错

### ISSUE THREAD

**Issue by Tamamoimoto** [cypress0522/AImage#5]
安装https://raw.sevencdn.com/Dice-Developer-Team/DiceModIndex/main/AImage失败:[json.exception.parse_error.101] parse error at line 1, column 4: syntax error while parsing value - unexpected ':'; expected end of input

安装https://raw.githubusercontent.com/Dice-Developer-Team/DiceModIndex/main/AImage失败:[json.exception.parse_error.101] parse error at line 1, column 4: syntax error while parsing value - unexpected ':'; expected end of input

安装https://ssjskfjdj.netlify.app/Module/AImage失败:[json.exception.parse_error.101] parse error at line 1, column 4: syntax error while parsing value - unexpected ':'; expected end of input

注入记忆体「AImage」失败×
https://raw.sevencdn.com/Dice-Developer-Team/DiceModIndex/main/AImage:[json.exception.parse_error.101] parse error at line 1, column 4: syntax error while parsing value - unexpected ':'; expected end of input
https://raw.githubusercontent.com/Dice-Developer-Team/DiceModIndex/main/AImage:[json.exception.parse_error.101] parse error at line 1, column 4: syntax error while parsing value - unexpected ':'; expected end of input
https://ssjskfjdj.netlify.app/Module/AImage:[json.exception.parse_error.101] parse error at line 1, column 4: syntax error while parsing value - unexpected ':'; expected end of input

**Comment by Tamamoimoto** [comment]
还有/i2i用这张图返回图片纯黑，
![R)BEXGBURWLYXUP5%BG6(KQ](https://user-images.githubusercontent.com/37890702/206839338-a3e2c6f3-ef54-4978-bccd-7c1396915b3d.jpg)
用bot的/t2i返回的图片使用/i2i是正常的。

**Comment by Tamamoimoto** [comment]
dice版本：2.6.6alpha(634)
linux版本：Linux armbian 5.15.58-flippy-75+o #148 SMP PREEMPT Sat Jul 30 11:32:27 CST 2022 aarch64 aarch64 aarch64 GNU/Linux

**Comment by HsiangNianian** [comment]
> 还有/i2i用这张图返回图片纯黑， ![R)BEXGBURWLYXUP5%BG6(KQ](https://user-images.githubusercontent.com/37890702/206839338-a3e2c6f3-ef54-4978-bccd-7c1396915b3d.jpg) 用bot的/t2i返回的图片使用/i2i是正常的。

```
【管理员】重子 15:54:03
https://github.com/cypress0522/AImage/issues/5

【管理员】重子 15:54:06
@阿尘

【管理员】重子 15:54:11
我该怎么回答

【笨蛋】阿尘 15:55:09
哦

【笨蛋】阿尘 15:55:15
输入图片太大了

【笨蛋】阿尘 15:55:20
显存扛不住
```

**Comment by HsiangNianian** [comment]
> 安装[https://raw.sevencdn.com/Dice-Developer-Team/DiceModIndex/main/AImage失败:[json.exception.parse_error.101]](https://raw.sevencdn.com/Dice-Developer-Team/DiceModIndex/main/AImage%E5%A4%B1%E8%B4%A5:%5Bjson.exception.parse_error.101%5D) parse error at line 1, column 4: syntax error while parsing value - unexpected ':'; expected end of input
> 
> 安装[https://raw.githubusercontent.com/Dice-Developer-Team/DiceModIndex/main/AImage失败:[json.exception.parse_error.101]](https://raw.githubusercontent.com/Dice-Developer-Team/DiceModIndex/main/AImage%E5%A4%B1%E8%B4%A5:%5Bjson.exception.parse_error.101%5D) parse error at line 1, column 4: syntax error while parsing value - unexpected ':'; expected end of input
> 
> 安装[https://ssjskfjdj.netlify.app/Module/AImage失败:[json.exception.parse_error.101]](https://ssjskfjdj.netlify.app/Module/AImage%E5%A4%B1%E8%B4%A5:%5Bjson.exception.parse_error.101%5D) parse error at line 1, column 4: syntax error while parsing value - unexpected ':'; expected end of input
> 
> 注入记忆体「AImage」失败× [https://raw.sevencdn.com/Dice-Developer-Team/DiceModIndex/main/AImage:[json.exception.parse_error.101]](https://raw.sevencdn.com/Dice-Developer-Team/DiceModIndex/main/AImage:%5Bjson.exception.parse_error.101%5D) parse error at line 1, column 4: syntax error while parsing value - unexpected ':'; expected end of input [https://raw.githubusercontent.com/Dice-Developer-Team/DiceModIndex/main/AImage:[json.exception.parse_error.101]](https://raw.githubusercontent.com/Dice-Developer-Team/DiceModIndex/main/AImage:%5Bjson.exception.parse_error.101%5D) parse error at line 1, column 4: syntax error while parsing value - unexpected ':'; expected end of input [https://ssjskfjdj.netlify.app/Module/AImage:[json.exception.parse_error.101]](https://ssjskfjdj.netlify.app/Module/AImage:%5Bjson.exception.parse_error.101%5D) parse error at line 1, column 4: syntax error while parsing value - unexpected ':'; expected end of input

1. 暂时移除<https://raw.sevencdn.com/Dice-Developer-Team/DiceModIndex/main/>源与<https://raw.githubusercontent.com/Dice-Developer-Team/DiceModIndex/main/>源，即确保`DiceQQ/conf/mod/source.list`文件内只有`https://ssjskfjdj.netlify.app/Module/`。
2. 接着删除本地`AImage`模块，删干净，把`AImage文件夹`还有`AImage.json`都删了。
3. 重载你的bot。
4. 输入`.mod get AImage`来获得最新版。

**Comment by HsiangNianian** [comment]
后续：

【笨蛋】阿尘 16:02:36
我屏幕都放不下

【笨蛋】阿尘 16:02:39
![HG3_DG`%0)%ML3XL5081BCI](https://user-images.githubusercontent.com/44714368/206840151-86db076b-5acb-4f7f-8d22-b161794ffbbc.jpg)


【管理员】重子 16:02:50
![H@G(758 P0JH{(BEG9A2{26](https://user-images.githubusercontent.com/44714368/206840149-2718ff53-438d-49af-adfe-35444815b750.gif)


【笨蛋】阿尘 16:02:52
![8E{C~BEV932(M%_ V8GY0DC](https://user-images.githubusercontent.com/44714368/206840145-b4ca8135-57d9-4cb3-922f-a59f86837d28.png)

怎么会有人塞这么大的吐

**Comment by Tamamoimoto** [comment]
乐hhh
